version: '3'
services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
      image: mongo:4.2
      networks:
        - graylog
      restart: always
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      deploy:
        resources:
          limits:
            memory: 1g
      networks:
        - graylog
      restart: always
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.3.3
      container_name: graylog
      environment:
        - TZ=America/Maceio
        - GRAYLOG_TIMEZONE=America/Maceio
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      networks:
        - graylog
      volumes:
        # - ./config/etc/timezone:/etc/timezone
        - ./config/etc/graylog/server:/etc/graylog/server
        - ./config/etc/graylog/graylog.conf:/usr/share/graylog/data/config/graylog.conf:ro
        
      restart: always
      depends_on:
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9001:9000
        # Syslog TCP
        - 514:514
        # Syslog UDP
        - 514:514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
        # Syslog UDP
        - 5442:5442/udp
    # ElasticSearch Web Admin Console
    cerebro:
      image: lmenezes/cerebro
      environment:
        - CEREBRO_PORT=9002
      depends_on:
        - elasticsearch
      ports:
        - 9002:9002
      networks:
        - graylog

    # Grafana Dashboard
    grafana:
      image: grafana/grafana-enterprise:8.2.0
      ports:
        - 3000:3000
      user: '104'
      networks:
        - graylog
      depends_on:
        - elasticsearch
      environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,savantly-heatmap-panel

networks:
    graylog:
      driver: bridge
